export const customerStatus = [
  "AGUARDANDO VISITA",
  "AGUARDANDO RESPOSTA",
  "SEM RESPOSTA",
  "REALIZAR REUNIÃO",
  "CONCLUÍDO COM SUCESSO",
  "CONCLUÍDO COM FALHA",
  "CANCELADO",
  "AGENDAR REUNIÃO",
] as const;
